/**
 * Central enumeration of all error codes used across the backend.
 * All codes are upper‑snake‑case strings.
 */
module.exports = Object.freeze({
  UPLOAD_ERROR: 'UPLOAD_ERROR',
  PROCESSING_ERROR: 'PROCESSING_ERROR',
  PREPROCESSING_ERROR: 'PREPROCESSING_ERROR',
  EXTRACTION_ERROR: 'EXTRACTION_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  SIGNING_ERROR: 'SIGNING_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR', // optional for fetch failures
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
});
